#!/bin/bash
cd ~/.mozilla/firefox/*.default-release/
cp chrome/* ~/.other/firefox/chrome/
#cp prefs.js ~/.other/firefox
cd /etc
sudo cp connman/main.conf ~/.other/etc/connman/
sudo cp dnscrypt-proxy/dnscrypt-proxy.toml ~/.other/etc/dnscrypt-proxy/
sudo cp modprobe.d/* ~/.other/etc/modprobe.d/
sudo cp sysctl.d/* ~/.other/etc/sysctl.d/
sudo cp udev/rules.d/* ~/.other/etc/udev/rules.d/
git --git-dir=$HOME/.cfg/ --work-tree=$HOME add -u
git --git-dir=$HOME/.cfg/ --work-tree=$HOME add ~/.other
git --git-dir=/home/nils/.cfg/ --work-tree=/home/nils reset ~/.scripts/backup.sh
git --git-dir=/home/nils/.cfg/ --work-tree=/home/nils reset ~/.scripts/musicupdate.sh
git --git-dir=$HOME/.cfg/ --work-tree=$HOME status
echo -e "\n\e[31m>>> don't commit sensitive data! check the added files. <<<\n\e[0m"
