#!/bin/bash
yay -Qeq > ~/.other/packages.txt
cd /etc
sudo cp systemd/resolved.conf ~/.other/etc/systemd/resolved.conf
sudo cp systemd/network/* ~/.other/etc/systemd/network/
sudo cp iwd/main.conf ~/.other/etc/iwd/main.conf
sudo cp modprobe.d/* ~/.other/etc/modprobe.d/
sudo cp sysctl.d/* ~/.other/etc/sysctl.d/
sudo cp udev/rules.d/51-android.rules ~/.other/etc/udev/rules.d/
sudo cp security/pam_env.conf ~/.other/etc/security/
sudo cp systemd/system/slock@nils.service ~/.other/etc/systemd/system/
git --git-dir=$HOME/.cfg/ --work-tree=$HOME add -u
git --git-dir=$HOME/.cfg/ --work-tree=$HOME add ~/.other
git --git-dir=$HOME/.cfg/ --work-tree=$HOME add ~/.scripts/
git --git-dir=$HOME/.cfg/ --work-tree=$HOME status
echo -e "\n\e[31m>>> don't commit sensitive data! check the added files. <<<\n\e[0m"
