#!/bin/bash
# source: https://github.com/LukeSmithxyz/voidrice/blob/archi3/.local/bin/tools/compiler

file=$(readlink -f "$1")
dir=$(dirname "$file")
base="${file%.*}"

cd "$dir" || exit

case "$file" in
	*\.tex) command="pdflatex"; $( sed 5q "$file" | grep -i -q 'xelatex' ) && command="xelatex"; $command --output-directory="$dir" "$base" ;;
esac
