#!/bin/bash
# send a notification when print job(s) complete(s)
# i'd advise only starting this script before a print job,
# because it's pretty expensive cpu-wise. when running lpq,
# a new cupsd instance is created, instead of reusing the
# already existing one. i've looked into dbus calls, but
# they don't really seem promising either... :/

set -eu -o pipefail

while true; do
  if [ "$(lpq | sed 1d)" == "no entries" ]; then
    # not printing
    continue
  elif [ ! "$(lpq | sed 1d)" == "no entries" ]; then
    # started printing
    NOT_FINISHED=true
    while $NOT_FINISHED; do
      # still printing
      if [ "$(lpq | sed 1d)" == "no entries" ]; then
        NOT_FINISHED=false
        notify-send -t 3000 "cupsnotifier" "print job(s) completed"
        exit 0
        # finished printing
      fi
      sleep 2
    done
  fi
  sleep 2
done
