#!/bin/bash
# wrapper for mons (https://aur.archlinux.org/packages/mons/) with audio output switching
# if audio doesn't work, try: pacmd list-cards

switchaudio() {
  read -rp "html audio: what thunderbolt port are you using (front|back)? " PORT
  if [ "$PORT" == "front" ];then
    sudo -u nils pactl --server "unix:/run/user/1000/pulse/native" set-card-profile 0 output:hdmi-stereo-extra1+input:analog-stereo
  elif [ "$PORT" == "back" ];then
    sudo -u nils pactl --server "unix:/run/user/1000/pulse/native" set-card-profile 0 output:hdmi-stereo+input:analog-stereo
  fi
}

case "$1" in
  m)
    killall redshift || true
    mons -m
    switchaudio
    echo "you might want to killall xautolock"
    echo "you might want to killall dunst"
    ;;
  e)
    if [ "$2" == "" ]; then
      SIDE="right"
    else
      SIDE="$2"
    fi
    killall redshift || true
    mons -e "$SIDE"
    switchaudio
    echo "you might want to killall xautolock"
    echo "you might want to killall dunst"
    ;;
  d)
    # re-enable redshift
    redshift -l "$(curl -s https://ipapi.co | grep -oP '(?<=<td class="ipval" data-clipboard-text=").*?(?=")' | sed -n 7p | sed 's/, /:/')" || true &
    mons -o
    if ! pgrep xautolock; then
      xautolock -time 2 -corners ---- -cornersize 40 -locker "/usr/bin/pactl set-sink-mute 0 toggle; systemctl suspend" -detectsleep -notify 15 -notifier "notify-send --urgency=critical 'suspending in 15s'" &
    fi
    if ! pgrep dunst; then
      dunst &
    fi
    sudo -u nils pactl --server "unix:/run/user/1000/pulse/native" set-card-profile 0 output:analog-stereo+input:analog-stereo
    sleep 4
    tput reset
    ;;
  *)
    echo -e "help:\n m - mirror this display.\n e [right/left] - extend (default is right).\n d - disconnect."
    exit 1
esac
