#!/bin/bash
# wrapper for mons (https://aur.archlinux.org/packages/mons/) with audio output switching
# if audio doesn't work, try: pacmd list-cards

switchaudio() {
  case "$(echo -e "far\nnear" | dmenu -p "audio: what thunderbolt port are you using?")" in
    far)
    sudo -u nils pactl --server "unix:/run/user/1000/pulse/native" set-card-profile 0 output:hdmi-stereo-extra1+input:analog-stereo ;;
    near)
    sudo -u nils pactl --server "unix:/run/user/1000/pulse/native" set-card-profile 0 output:hdmi-stereo+input:analog-stereo ;;
  esac
}

case "$1" in
  m)
    mons -m
    switchaudio
    ;;
  e)
    if [ "$2" == "" ]; then
      SIDE="right"
    else
      SIDE="$2"
    fi
    mons -e "$SIDE"
    switchaudio
    ;;
  d)
    mons -o
    sudo -u nils pactl --server "unix:/run/user/1000/pulse/native" set-card-profile 0 output:analog-stereo+input:analog-stereo
    ;;
  *)
    echo -e "help:\n m - mirror this display.\n e [right/left] - extend (default is right).\n d - disconnect."
    exit 1
esac
