#!/bin/bash
# weather is cached at ~/.cache/panelweathercached.txt

function weather() {
# pad weather info to longest row length, so that paste works
# takes too long to do ad-hoc. refreshed every X minutes via cron
  rawweather="$(curl -s "https://wttr.in/?0?F?T?A" | sed 's/report:/in/;s/, .*$//')"
  readarray -t rweather <<< "$rawweather"
  longest="$(wc -L <<< "$rawweather")"
  fweather=""

  # use last weather, if not net
  [[ -z "$rawweather" ]] && exit 0

  for row in "${rweather[@]}"; do

    while [ $(wc -L <<< "$row") -lt $longest ]; do
      row+=" "
    done
    fweather+="$row%"
  done
  echo "$fweather" | tr '%' '\n' | sed '$d' > ~/.cache/panelweathercached.txt

  finalline=" "
  while [ $(wc -L <<< "$finalline") -lt $longest ]; do
    finalline+=" "
  done
  echo "$finalline" >> ~/.cache/panelweathercached.txt
}

function main() {
  # cheap cowsay, § is temporarily used bc | is later used by paste as a delimiter
  cow=$(echo -e " ____________________ \n< have a nice day :) >\n -------------------- \n        \   ^__^\n         \  (oo)\_______\n            (__)\       )\/\ \n                §§----w §\n                §§     §§")
  
  # paste (prev month) (paste (week numbers this month) (cat (this month cal header) (this month cal without header, date highlighted))) (next month)
  datecal=$(paste -d ' ' <(cal -3 -mw | cut -c 1-24) <(paste -d "" <(cal -mw | cut -c 1-3) <(cat <(cal -m | head -n 1) <( cal -n 2 -mw | cut -c 4-23 | sed 1d | sed "0,/$(date +%d | sed -r 's/^0(.)/\1/')/s/$(date +%d | sed 's/^0/ /')/></"))) <(cal -n 2 -mw | cut -c 25-48) | sed 's/   Mo/WK Mo/g')

  # hex 222222 so that the selected line doesnt jump out
  paste -d '|' <(echo "$datecal") ~/.cache/panelweathercached.txt <(echo "$cow") | sed 's/|/  |  /g;s/^/ /g;s/§/|/g' | cat <(printf '\n') - <(printf '\n') | dmenu -sb "#222222" -l 10
}

case $1 in
  weather)
    weather;;
  run)
    main;;
  *)
    echo "valid cli args are weather and run. weather should be called from cronjob." && exit 1;;
esac

