#!/bin/bash
# inspired by: https://en.wikipedia.org/wiki/Netcat#Setting_up_a_one-shot_webserver_on_port_8080_to_present_the_content_of_a_file
# usage: ./lanshare.sh <FILE PATH>
# on other device: visit http://LAN-IP:8005

[[ -z "$1" ]] && echo "no file provided." && exit 1

FILE="$1"
FILEID="$(shuf -n 1 -i 10000-99999)" # try to avoid file name collisions
FILEEXT="$(basename "$FILE" | sed 's/.*\.//')"
echo "$(hostname --ip-address)"":8005"
{ echo -ne "HTTP/1.0 200 OK\r\nContent-Length: $(wc -c < "$FILE")\r\nContent-Disposition: attachment; filename=file-"$FILEID"."$FILEEXT"\r\n\r\n"; cat "$FILE"; } | ncat -l -p 8005
