#!/bin/sh
# Checks for internet connection and set notification script.
ping -q -c 1 1.1.1.1 > /dev/null || exit
export DISPLAY=:0.0

notify() { notify-send "neomutt" "$2 new mail(s) [$1]" ;}

mbsync -a

# Check all accounts/mailboxes for new mail. Notify if there is new content.
for account in "$HOME/.local/share/mail/"*
do
	acc="$(echo "$account" | sed "s/.*\///")"
	newcount=$(find "$HOME/.local/share/mail/$acc/INBOX/new/" "$HOME/.local/share/mail/$acc/Inbox/new/" "$HOME/.local/share/mail/$acc/inbox/new/" -type f -newer "$HOME/.config/mutt/.mailsynclastrun" 2> /dev/null | wc -l)
	[ "$newcount" -gt "0" ] && notify "$acc" "$newcount" &
done
notmuch new 2>/dev/null

exec neomutt
