#!/bin/bash
# adapted from: https://github.com/LukeSmithxyz/voidrice/blob/archi3/.local/bin/tools/compiler


case "$1" in

file=$(readlink -f "$1")
dir=$(dirname "$file")
base="${file%.*}"

cd "$dir" || exit

compile)
case "$file" in
	*\.tex) command="pdflatex"; $( sed 5q "$file" | grep -i -q 'xelatex' ) && command="xelatex"; $command --output-directory="$dir" "$base" ;;
esac

latexenv) kitty -c zathura $base.pdf & ;;

esac
