#!/bin/bash

case "$1" in
  start)
    echo "stopping services..."
    killall redshift || true
    killall dunst || true
    echo "disabling cronjobs..."
    crontab -l > ~/.cronbackup
    crontab -r
    ;;
  stop)
    echo "restarting services..."
    redshift </dev/null &>/dev/null &
    dunst </dev/null &>/dev/null &
    xautolock -time 2 -corners ---- -cornersize 40 -locker "/usr/bin/pactl set-sink-mute 0 toggle; systemctl suspend" -detectsleep -notify 15 -notifier "notify-send --urgency=critical 'suspending in 15s'" </dev/null &>/dev/null &
    echo "sudo for re-installing crontab..."
    cat ~/.cronbackup
    sudo mv ~/.cronbackup /var/spool/cron/nils
    echo -e "\n\tMOVED\n"
    crontab -l
    echo "please check the crontab!"
    ;;
esac
