#!/bin/bash

case "$1" in
  start)
    echo "stopping services..."
    killall redshift || true
    dunstctl set-paused true
    echo "disabling cronjobs..."
    crontab -l > ~/.cronbackup && crontab -r
    ;;
  stop)
    echo "restarting services..."
    redshift </dev/null &>/dev/null &
    dunstctl set-paused false
    echo "sudo for re-installing crontab..."
    cat ~/.cronbackup
    sudo mv ~/.cronbackup /var/spool/cron/nils
    echo -e "\n\tMOVED\n"
    crontab -l
    echo "please check the crontab!"
    ;;
esac
