#!/bin/sh
set -x

esprstate="$(cat ~/.cache/dwmespresso.txt)"

case "$(echo -e "calculator\nnew wallpaper\npass\nopen file\n\nespresso [$esprstate]\nbt connect\nbt disconnect\n\nlock screen\nsuspend\nreboot\nshutdown\n" | dmenu -i -p "utility menu:" -l 16 )" in
        calculator) kitty bc -l ;;
        new\ wallpaper) $HOME/.scripts/fehbg ;;
        pass) $HOME/.scripts/passnosave ;;
        open\ file) kitty $HOME/.scripts/search-and-open & ;;
        espresso\ \[$esprstate\]) $HOME/.scripts/espresso ;;
        bt\ connect) $HOME/.scripts/btmenu ;;
        bt\ disconnect) $HOME/.scripts/btmenu -d ;;
        lock\ screen) exec slock ;;
        suspend) exec systemctl suspend ;;
        reboot) exec systemctl reboot ;;
        shutdown) exec systemctl poweroff ;;
esac
