#!/bin/sh
    
case "$(echo -e "calculator\nnew wallpaper\npass\nscreenshot\n\nbt connect\nbt disconnect\nwifictrl\n\nlock screen\nsuspend\nreboot\nshutdown" | dmenu -i -p "utility menu:" -l 13  )" in
        calculator) kitty bc -l ;;
        new\ wallpaper) $HOME/.scripts/fehbg ;;
        pass) $HOME/.scripts/passnosave ;;
        screenshot) $HOME/.scripts/screenshot ;;
        bt\ connect) $HOME/.scripts/btmenu ;;
        bt\ disconnect) $HOME/.scripts/btmenu -d ;;
        wifictrl) kitty $HOME/.scripts/guidedconnman ;;
        lock\ screen) /usr/bin/pactl set-sink-mute 0 toggle; exec slock ;;
        suspend) exec systemctl suspend ;;
        reboot) exec systemctl reboot ;;
        shutdown) exec systemctl poweroff ;;
esac
