#!/bin/sh
    
case "$(echo -e "calculator\npassword store" | wofi -p "utility menu:" )" in
        #new\ wallpaper) $HOME/.scripts/gnome-bg ;;
        calculator) kitty bc -l $HOME/.config/bcrc ;;
        password\ store) $HOME/.scripts/passnosave-gnome ;;
esac
