#!/bin/sh

SINK=$(pacmd list-sinks|awk '/\* index:/{ print $3 }')

if [ "$1" == "up" ]; then
  pactl set-sink-volume "$SINK" +5%
elif [ "$1" == "down" ]; then
  pactl set-sink-volume "$SINK" -5%
elif [ "$1" == "togglemute" ]; then
  pactl set-sink-mute "$SINK" toggle
fi

~/.xsession barupdate
